//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTMLSnippetShare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HTMLCode
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        public string HTML { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public int UserId { get; set; }

        public virtual User User { get; set; }
    }
}